[template]
cargo_generate_version = ">=0.10.0"

[placeholders.app_name]
type = "string"
prompt = "What is the name of your application?"
default = "my-hello-app"

[placeholders.description]
type = "string"
prompt = "Describe your project"
default = "A Foundry + Rust Hello World project" 